# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ifelseCNum <- function(test, yes, no) {
    .Call('_NETT_ifelseCNum', PACKAGE = 'NETT', test, yes, no)
}

ifelseCLogic <- function(test, yes, no) {
    .Call('_NETT_ifelseCLogic', PACKAGE = 'NETT', test, yes, no)
}

ifelseCInt <- function(test, yes, no) {
    .Call('_NETT_ifelseCInt', PACKAGE = 'NETT', test, yes, no)
}

ifelseCChar <- function(test, yes, no) {
    .Call('_NETT_ifelseCChar', PACKAGE = 'NETT', test, yes, no)
}

